(AB#5179) Add class-based DSC Resource tutorial
MicrosoftDocs/PowerShell-Docs-DSC pull request #107
Opened 2022-09-16 21:58 UTC by michaeltlombardi

# PR Summary

This change introduces a new tutorial for authoring a class-based DSC Resource, taking the user from zero to a functional DSC Resource exported from a PowerShell module.

- Fixes AB#5179

## PR Checklist

- [x] **Descriptive Title:** This PR's title is a synopsis of the changes it proposes.
- [x] **Summary:** This PR's summary describes the scope and intent of the change.
- [x] **Contributor's Guide:** I have read the [contributors guide][contrib].
- [x] **Style:** This PR adheres to the [style guide][style].

[contrib]: https://docs.microsoft.com/powershell/scripting/community/contributing/overview
[style]: https://docs.microsoft.com/powershell/scripting/community/contributing/powershell-style-guide

2022-09-16 22:00 UTC, opbld32 commented
Docs Build status updates of commit _[509f2c0](https://github.com/michaeltlombardi/PowerShell-Docs-DSC/commits/509f2c06ed08522a0bf986a9770f35c35eb5c62a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[dsc/docs-conceptual/dsc-2.0/quickstarts/basic-dsc-resource.md](https://github.com/michaeltlombardi/PowerShell-Docs-DSC/blob/ab-5169/main/dsc-tutorial/dsc/docs-conceptual/dsc-2.0/quickstarts/basic-dsc-resource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/dsc/quickstarts/basic-dsc-resource?view=dsc-2.0&branch=pr-en-us-107) (dsc-2.0) | [Details](#user-content-925fa666372731bfde1ea35be7d653d5-c6240c27)
[dsc/docs-conceptual/dsc-2.0/quickstarts/media/basic-dsc-resource/Empty-Class-Warnings.png](https://github.com/michaeltlombardi/PowerShell-Docs-DSC/blob/ab-5169/main/dsc-tutorial/dsc/docs-conceptual/dsc-2.0/quickstarts/media/basic-dsc-resource/Empty-Class-Warnings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/dsc/quickstarts/basic-dsc-resource?view=dsc-2.0&branch=pr-en-us-107) (dsc-2.0) |

<a id="925fa666372731bfde1ea35be7d653d5-c6240c27"></a>
### [dsc/docs-conceptual/dsc-2.0/quickstarts/basic-dsc-resource.md](https://github.com/michaeltlombardi/PowerShell-Docs-DSC/blob/ab-5169/main/dsc-tutorial/dsc/docs-conceptual/dsc-2.0/quickstarts/basic-dsc-resource.md)
 - **Line 852, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'contribute-how-to-mvc-tutorial.md'.`````
 - **Line 843, Column 2**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'resources' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/5e2f03cc-63f1-1428-f12c-c00198b87edc/202209162158562692-107/BuildReport?accessString=1a7a5214d3926c1fd22a8f4d55bf628b40f92497b1156477e1709694088cabef).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/5e2f03cc-63f1-1428-f12c-c00198b87edc?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-16 22:01 UTC, opbld30 commented
Docs Build status updates of commit _[c3ed563](https://github.com/michaeltlombardi/PowerShell-Docs-DSC/commits/c3ed563025f238e28bf549a13963ae7f385b7e1d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[dsc/docs-conceptual/dsc-2.0/quickstarts/basic-dsc-resource.md](https://github.com/michaeltlombardi/PowerShell-Docs-DSC/blob/ab-5169/main/dsc-tutorial/dsc/docs-conceptual/dsc-2.0/quickstarts/basic-dsc-resource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/dsc/quickstarts/basic-dsc-resource?view=dsc-2.0&branch=pr-en-us-107) (dsc-2.0) | [Details](#user-content-925fa666372731bfde1ea35be7d653d5-a8d80e0f)
[dsc/docs-conceptual/dsc-2.0/quickstarts/media/basic-dsc-resource/Empty-Class-Warnings.png](https://github.com/michaeltlombardi/PowerShell-Docs-DSC/blob/ab-5169/main/dsc-tutorial/dsc/docs-conceptual/dsc-2.0/quickstarts/media/basic-dsc-resource/Empty-Class-Warnings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/dsc/quickstarts/basic-dsc-resource?view=dsc-2.0&branch=pr-en-us-107) (dsc-2.0) |

<a id="925fa666372731bfde1ea35be7d653d5-a8d80e0f"></a>
### [dsc/docs-conceptual/dsc-2.0/quickstarts/basic-dsc-resource.md](https://github.com/michaeltlombardi/PowerShell-Docs-DSC/blob/ab-5169/main/dsc-tutorial/dsc/docs-conceptual/dsc-2.0/quickstarts/basic-dsc-resource.md)
 - **Line 852, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'contribute-how-to-mvc-tutorial.md'.`````
 - **Line 843, Column 2**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'resources' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/5e2f03cc-63f1-1428-f12c-c00198b87edc/202209162159210527-107/BuildReport?accessString=0ae4299cb531fee89746e9203b3557cf5799d1cfca21895bdb622d2daa12f071).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/5e2f03cc-63f1-1428-f12c-c00198b87edc?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-16 22:03 UTC, opbld30 commented
Docs Build status updates of commit _[324215a](https://github.com/michaeltlombardi/PowerShell-Docs-DSC/commits/324215a4d0e1d82bc6379909ebe3e7609f7834d4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[dsc/docs-conceptual/dsc-2.0/toc.yml](https://github.com/michaeltlombardi/PowerShell-Docs-DSC/blob/ab-5169/main/dsc-tutorial/dsc/docs-conceptual/dsc-2.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/dsc/tutorials/basic-dsc-resource?view=dsc-2.0&branch=pr-en-us-107) (dsc-2.0) |
[dsc/docs-conceptual/dsc-2.0/tutorials/basic-dsc-resource.md](https://github.com/michaeltlombardi/PowerShell-Docs-DSC/blob/ab-5169/main/dsc-tutorial/dsc/docs-conceptual/dsc-2.0/tutorials/basic-dsc-resource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/dsc/tutorials/basic-dsc-resource?view=dsc-2.0&branch=pr-en-us-107) (dsc-2.0) |
[dsc/docs-conceptual/dsc-2.0/tutorials/media/basic-dsc-resource/Empty-Class-Warnings.png](https://github.com/michaeltlombardi/PowerShell-Docs-DSC/blob/ab-5169/main/dsc-tutorial/dsc/docs-conceptual/dsc-2.0/tutorials/media/basic-dsc-resource/Empty-Class-Warnings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/dsc/tutorials/basic-dsc-resource?view=dsc-2.0&branch=pr-en-us-107) (dsc-2.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/5e2f03cc-63f1-1428-f12c-c00198b87edc/202209162202119576-107/BuildReport?accessString=66cf422339da78fe5e092491500749a346f09214eb73b7969529022a47143d37).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/5e2f03cc-63f1-1428-f12c-c00198b87edc?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-10-13 20:09 UTC, opbld31 commented
Learn Build status updates of commit _[55fbed5](https://github.com/michaeltlombardi/PowerShell-Docs-DSC/commits/55fbed5014787d97746946716a0daad85e3ecd9d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[dsc/docs-conceptual/dsc-2.0/toc.yml](https://github.com/michaeltlombardi/PowerShell-Docs-DSC/blob/ab-5169/main/dsc-tutorial/dsc/docs-conceptual/dsc-2.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/dsc/tutorials/basic-dsc-resource?view=dsc-2.0&branch=pr-en-us-107) (dsc-2.0) |
[dsc/docs-conceptual/dsc-2.0/tutorials/basic-dsc-resource.md](https://github.com/michaeltlombardi/PowerShell-Docs-DSC/blob/ab-5169/main/dsc-tutorial/dsc/docs-conceptual/dsc-2.0/tutorials/basic-dsc-resource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/dsc/tutorials/basic-dsc-resource?view=dsc-2.0&branch=pr-en-us-107) (dsc-2.0) |
[dsc/docs-conceptual/dsc-2.0/tutorials/media/basic-dsc-resource/Empty-Class-Warnings.png](https://github.com/michaeltlombardi/PowerShell-Docs-DSC/blob/ab-5169/main/dsc-tutorial/dsc/docs-conceptual/dsc-2.0/tutorials/media/basic-dsc-resource/Empty-Class-Warnings.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/dsc/tutorials/basic-dsc-resource?view=dsc-2.0&branch=pr-en-us-107) (dsc-2.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/5e2f03cc-63f1-1428-f12c-c00198b87edc/202210132008068521-107/BuildReport?accessString=8a9eb0520d40592078e15754d15891f39934b00d7a6d3b4a00125ab29dfaf7b9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/5e2f03cc-63f1-1428-f12c-c00198b87edc?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-13 22:04 UTC, sdwheeler requested changes

2022-10-14 21:16 UTC, opbld30 commented
Learn Build status updates of commit _[f4c808b](https://github.com/michaeltlombardi/PowerShell-Docs-DSC/commits/f4c808bfe872bd77fba3952878c6289636a68b57)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[dsc/docs-conceptual/dsc-2.0/toc.yml](https://github.com/michaeltlombardi/PowerShell-Docs-DSC/blob/ab-5169/main/dsc-tutorial/dsc/docs-conceptual/dsc-2.0/toc.yml) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/powershell/dsc/tutorials/create-class-based-resource?view=dsc-2.0&branch=pr-en-us-107) (dsc-2.0) | [Details](#user-content-8eb30460e0d0b9f9923ff0c7c2716490-1cb242ed)
[dsc/docs-conceptual/dsc-2.0/tutorials/create-class-based-resource.md](https://github.com/michaeltlombardi/PowerShell-Docs-DSC/blob/ab-5169/main/dsc-tutorial/dsc/docs-conceptual/dsc-2.0/tutorials/create-class-based-resource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/dsc/tutorials/create-class-based-resource?view=dsc-2.0&branch=pr-en-us-107) (dsc-2.0) |
[dsc/docs-conceptual/dsc-2.0/tutorials/media/create-class-based-resource/Empty-Class-Warnings.png](https://github.com/michaeltlombardi/PowerShell-Docs-DSC/blob/ab-5169/main/dsc-tutorial/dsc/docs-conceptual/dsc-2.0/tutorials/media/create-class-based-resource/Empty-Class-Warnings.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/dsc/tutorials/create-class-based-resource?view=dsc-2.0&branch=pr-en-us-107) (dsc-2.0) |

<a id="8eb30460e0d0b9f9923ff0c7c2716490-1cb242ed"></a>
### [dsc/docs-conceptual/dsc-2.0/toc.yml](https://github.com/michaeltlombardi/PowerShell-Docs-DSC/blob/ab-5169/main/dsc-tutorial/dsc/docs-conceptual/dsc-2.0/toc.yml)
 - **Line 27, Column 11**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'tutorials/basic-dsc-resource.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/5e2f03cc-63f1-1428-f12c-c00198b87edc/202210142115367900-107/BuildReport?accessString=1e979a4b18134bf63d9a11a918416f19dc55cb4a429288f9846fc70b5f21ee5a).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/5e2f03cc-63f1-1428-f12c-c00198b87edc?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-14 21:21 UTC, michaeltlombardi commented on dsc/docs-conceptual/dsc-2.0/toc.yml
> +          href: tutorials/basic-dsc-resource.md
Done.

2022-10-14 21:22 UTC, opbld33 commented
Learn Build status updates of commit _[0190560](https://github.com/michaeltlombardi/PowerShell-Docs-DSC/commits/01905600b3090115214fa9f9d2cb2db0192a4710)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[dsc/docs-conceptual/dsc-2.0/toc.yml](https://github.com/michaeltlombardi/PowerShell-Docs-DSC/blob/ab-5169/main/dsc-tutorial/dsc/docs-conceptual/dsc-2.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/dsc/tutorials/create-class-based-resource?view=dsc-2.0&branch=pr-en-us-107) (dsc-2.0) |
[dsc/docs-conceptual/dsc-2.0/tutorials/create-class-based-resource.md](https://github.com/michaeltlombardi/PowerShell-Docs-DSC/blob/ab-5169/main/dsc-tutorial/dsc/docs-conceptual/dsc-2.0/tutorials/create-class-based-resource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/dsc/tutorials/create-class-based-resource?view=dsc-2.0&branch=pr-en-us-107) (dsc-2.0) |
[dsc/docs-conceptual/dsc-2.0/tutorials/media/create-class-based-resource/Empty-Class-Warnings.png](https://github.com/michaeltlombardi/PowerShell-Docs-DSC/blob/ab-5169/main/dsc-tutorial/dsc/docs-conceptual/dsc-2.0/tutorials/media/create-class-based-resource/Empty-Class-Warnings.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/dsc/tutorials/create-class-based-resource?view=dsc-2.0&branch=pr-en-us-107) (dsc-2.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/5e2f03cc-63f1-1428-f12c-c00198b87edc/202210142121028358-107/BuildReport?accessString=2f1d42eb4e1a007f9e683296feb99b8ad4e6da68be10506847f2fa15c9ea58c8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/5e2f03cc-63f1-1428-f12c-c00198b87edc?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-14 21:25 UTC, opbld33 commented
Learn Build status updates of commit _[0190560](https://github.com/michaeltlombardi/PowerShell-Docs-DSC/commits/01905600b3090115214fa9f9d2cb2db0192a4710)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[dsc/docs-conceptual/dsc-2.0/toc.yml](https://github.com/michaeltlombardi/PowerShell-Docs-DSC/blob/ab-5169/main/dsc-tutorial/dsc/docs-conceptual/dsc-2.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/dsc/tutorials/create-class-based-resource?view=dsc-2.0&branch=pr-en-us-107) (dsc-2.0) |
[dsc/docs-conceptual/dsc-2.0/tutorials/create-class-based-resource.md](https://github.com/michaeltlombardi/PowerShell-Docs-DSC/blob/ab-5169/main/dsc-tutorial/dsc/docs-conceptual/dsc-2.0/tutorials/create-class-based-resource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/dsc/tutorials/create-class-based-resource?view=dsc-2.0&branch=pr-en-us-107) (dsc-2.0) |
[dsc/docs-conceptual/dsc-2.0/tutorials/media/create-class-based-resource/Empty-Class-Warnings.png](https://github.com/michaeltlombardi/PowerShell-Docs-DSC/blob/ab-5169/main/dsc-tutorial/dsc/docs-conceptual/dsc-2.0/tutorials/media/create-class-based-resource/Empty-Class-Warnings.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/dsc/tutorials/create-class-based-resource?view=dsc-2.0&branch=pr-en-us-107) (dsc-2.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/5e2f03cc-63f1-1428-f12c-c00198b87edc/202210142123501277-107/BuildReport?accessString=2e45435c25ee192ed982e5fc64c260497363b86f61abcaac03d66dbe07c4f49f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/5e2f03cc-63f1-1428-f12c-c00198b87edc?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-14 21:35 UTC, opbld32 commented
Learn Build status updates of commit _[7244d7d](https://github.com/michaeltlombardi/PowerShell-Docs-DSC/commits/7244d7dadcfc3f5432ee08aadc5aa50038d115c9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[dsc/docs-conceptual/dsc-2.0/toc.yml](https://github.com/michaeltlombardi/PowerShell-Docs-DSC/blob/ab-5169/main/dsc-tutorial/dsc/docs-conceptual/dsc-2.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/dsc/tutorials/basic-dsc-resource?view=dsc-2.0&branch=pr-en-us-107) (dsc-2.0) |
[dsc/docs-conceptual/dsc-2.0/tutorials/basic-dsc-resource.md](https://github.com/michaeltlombardi/PowerShell-Docs-DSC/blob/ab-5169/main/dsc-tutorial/dsc/docs-conceptual/dsc-2.0/tutorials/basic-dsc-resource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/dsc/tutorials/basic-dsc-resource?view=dsc-2.0&branch=pr-en-us-107) (dsc-2.0) |
[dsc/docs-conceptual/dsc-2.0/tutorials/create-class-based-resource.md](https://github.com/michaeltlombardi/PowerShell-Docs-DSC/blob/ab-5169/main/dsc-tutorial/dsc/docs-conceptual/dsc-2.0/tutorials/create-class-based-resource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/dsc/tutorials/create-class-based-resource?view=dsc-2.0&branch=pr-en-us-107) (dsc-2.0) |
[dsc/docs-conceptual/dsc-2.0/tutorials/media/basic-dsc-resource/Empty-Class-Warnings.png](https://github.com/michaeltlombardi/PowerShell-Docs-DSC/blob/ab-5169/main/dsc-tutorial/dsc/docs-conceptual/dsc-2.0/tutorials/media/basic-dsc-resource/Empty-Class-Warnings.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/dsc/tutorials/basic-dsc-resource?view=dsc-2.0&branch=pr-en-us-107) (dsc-2.0) |
[dsc/docs-conceptual/dsc-2.0/tutorials/media/create-class-based-resource/Empty-Class-Warnings.png](https://github.com/michaeltlombardi/PowerShell-Docs-DSC/blob/ab-5169/main/dsc-tutorial/dsc/docs-conceptual/dsc-2.0/tutorials/media/create-class-based-resource/Empty-Class-Warnings.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/dsc/tutorials/create-class-based-resource?view=dsc-2.0&branch=pr-en-us-107) (dsc-2.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/5e2f03cc-63f1-1428-f12c-c00198b87edc/202210142134275436-107/BuildReport?accessString=08d7de861ea0b6a50d931823ad570f0ac83caa8fa82fc616c729c28bc768c4a6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/5e2f03cc-63f1-1428-f12c-c00198b87edc?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-17 21:12 UTC, opbld30 commented
Learn Build status updates of commit _[775ed57](https://github.com/michaeltlombardi/PowerShell-Docs-DSC/commits/775ed578e1d71793d41f4b382989bb2c0428069a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[dsc/docs-conceptual/dsc-2.0/toc.yml](https://github.com/michaeltlombardi/PowerShell-Docs-DSC/blob/ab-5169/main/dsc-tutorial/dsc/docs-conceptual/dsc-2.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/dsc/tutorials/create-class-based-resource?view=dsc-2.0&branch=pr-en-us-107) (dsc-2.0) |
[dsc/docs-conceptual/dsc-2.0/tutorials/create-class-based-resource.md](https://github.com/michaeltlombardi/PowerShell-Docs-DSC/blob/ab-5169/main/dsc-tutorial/dsc/docs-conceptual/dsc-2.0/tutorials/create-class-based-resource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/dsc/tutorials/create-class-based-resource?view=dsc-2.0&branch=pr-en-us-107) (dsc-2.0) |
[dsc/docs-conceptual/dsc-2.0/tutorials/media/create-class-based-resource/Empty-Class-Warnings.png](https://github.com/michaeltlombardi/PowerShell-Docs-DSC/blob/ab-5169/main/dsc-tutorial/dsc/docs-conceptual/dsc-2.0/tutorials/media/create-class-based-resource/Empty-Class-Warnings.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/dsc/tutorials/create-class-based-resource?view=dsc-2.0&branch=pr-en-us-107) (dsc-2.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/5e2f03cc-63f1-1428-f12c-c00198b87edc/202210172111561291-107/BuildReport?accessString=50fb212023290d293f38b1c26bffa7e4cc6d2b3548bb0467b1d4d05a31303e6d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/5e2f03cc-63f1-1428-f12c-c00198b87edc?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-18 16:41 UTC, opbld31 commented
Learn Build status updates of commit _[a549e48](https://github.com/michaeltlombardi/PowerShell-Docs-DSC/commits/a549e4847fdc549c9eae9ddf0064f72f0229c7ad)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[dsc/docs-conceptual/dsc-2.0/toc.yml](https://github.com/michaeltlombardi/PowerShell-Docs-DSC/blob/ab-5169/main/dsc-tutorial/dsc/docs-conceptual/dsc-2.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/dsc/tutorials/create-class-based-resource?view=dsc-2.0&branch=pr-en-us-107) (dsc-2.0) |
[dsc/docs-conceptual/dsc-2.0/tutorials/create-class-based-resource.md](https://github.com/michaeltlombardi/PowerShell-Docs-DSC/blob/ab-5169/main/dsc-tutorial/dsc/docs-conceptual/dsc-2.0/tutorials/create-class-based-resource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/dsc/tutorials/create-class-based-resource?view=dsc-2.0&branch=pr-en-us-107) (dsc-2.0) |
[dsc/docs-conceptual/dsc-2.0/tutorials/media/create-class-based-resource/Empty-Class-Warnings.png](https://github.com/michaeltlombardi/PowerShell-Docs-DSC/blob/ab-5169/main/dsc-tutorial/dsc/docs-conceptual/dsc-2.0/tutorials/media/create-class-based-resource/Empty-Class-Warnings.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/dsc/tutorials/create-class-based-resource?view=dsc-2.0&branch=pr-en-us-107) (dsc-2.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/5e2f03cc-63f1-1428-f12c-c00198b87edc/202210181641007586-107/BuildReport?accessString=3f23faf2214100ffb8a3112704198714d040f40dd64f4c7976eb4bd98070c382).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/5e2f03cc-63f1-1428-f12c-c00198b87edc?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-18 17:15 UTC, opbld31 commented
Learn Build status updates of commit _[220c5ee](https://github.com/michaeltlombardi/PowerShell-Docs-DSC/commits/220c5eeee75502f67d386620df7bfd8989763936)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[dsc/docs-conceptual/dsc-2.0/toc.yml](https://github.com/michaeltlombardi/PowerShell-Docs-DSC/blob/ab-5169/main/dsc-tutorial/dsc/docs-conceptual/dsc-2.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/dsc/tutorials/create-class-based-resource?view=dsc-2.0&branch=pr-en-us-107) (dsc-2.0) |
[dsc/docs-conceptual/dsc-2.0/tutorials/create-class-based-resource.md](https://github.com/michaeltlombardi/PowerShell-Docs-DSC/blob/ab-5169/main/dsc-tutorial/dsc/docs-conceptual/dsc-2.0/tutorials/create-class-based-resource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/dsc/tutorials/create-class-based-resource?view=dsc-2.0&branch=pr-en-us-107) (dsc-2.0) |
[dsc/docs-conceptual/dsc-2.0/tutorials/media/create-class-based-resource/Empty-Class-Warnings.png](https://github.com/michaeltlombardi/PowerShell-Docs-DSC/blob/ab-5169/main/dsc-tutorial/dsc/docs-conceptual/dsc-2.0/tutorials/media/create-class-based-resource/Empty-Class-Warnings.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/dsc/tutorials/create-class-based-resource?view=dsc-2.0&branch=pr-en-us-107) (dsc-2.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/5e2f03cc-63f1-1428-f12c-c00198b87edc/202210181713523576-107/BuildReport?accessString=4d700da15f4c13aea03a61c3b3437fc83b0c456ef175b8e6bb6c18276add09b2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/5e2f03cc-63f1-1428-f12c-c00198b87edc?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-18 17:20 UTC, merged